development:
  adapter: postgresql
  encoding: utf8
  database: vekii_development
  pool: 5
  username: postgres
  password: ufc1UF@12

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: vekiii_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: vekii_production
  pool: 5
  username: postgres
  password: